server:
  port: 8082
spring:
    application:
      name: sumkin-middle-service
    datasource:
      url: jdbc:postgresql://localhost:5446/gpbdb?schema=gpb
      username: {POSTGRES_USER}
      password: {POSTGRES_PASSWORD}
    sql:
      init:
        mode: always
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true



